apiVersion: v1
kind: Service

metadata:
  name: mongodb-service

spec:
  selector:
    app: mongodb # make sure this is same as the app in deployment.yaml file
  
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017