pipeline {
  agent any
  environment {
    IMAGE_NAME = "delivery_exporter:latest"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build Docker Image') {
      steps {
        sh """
          cd INTERNALS/exercise6-monitoring/delivery-monitoring
          docker build -t ${IMAGE_NAME} .
        """
      }
    }

    stage('Deploy Exporter') {
      steps {
        sh """
          docker rm -f delivery_exporter || true
          docker run -d --name delivery_exporter -p 8000:8000 ${IMAGE_NAME}
        """
      }
    }

    stage('Deploy Prometheus & Grafana') {
      steps {
        sh """
          docker rm -f prometheus || true
          docker rm -f grafana || true

          docker run -d --name prometheus -p 9090:9090 \
            -v $$WORKSPACE/INTERNALS/exercise6-monitoring/delivery-monitoring:/etc/prometheus \
            prom/prometheus

          docker run -d --name grafana -p 3000:3000 grafana/grafana
        """
      }
    }
  }

  post {
    success {
      echo "Monitoring stack deployed successfully!"
    }
    failure {
      echo "Pipeline failed!"
    }
  }
}
